import { Product } from "./types/Product";

export const sampleProducts:Product[] = [
    {
        name: 'Nike Slim Shirt',
        slug: 'nike-slim-shirt',
        image: '../images/p1.jpg',
        category: 'Shirts',
        brand: 'NIKE',
        price: 120,
        countInStock: 10,
        description: 'High Quality Material',
        rating: 4,
        numReviews: 10,
    },
    {
        name: 'lacoste Slim Shirt',
        slug: 'lacoste-slim-shirt',
        image: '../images/p2.jpg',
        category: 'Shirts',
        brand: 'NIKE',
        price: 120,
        countInStock: 10,
        description: 'High Quality Material',
        rating: 4,
        numReviews: 10,
    },
    {
        name: 'Lacoste Slim Shirt',
        slug: 'lacoste-slim-shirt1',
        image: '../images/p3.jpg',
        category: 'Pants',
        brand: 'NIKE',
        price: 120,
        countInStock: 10,
        description: 'High Quality Material',
        rating: 4,
        numReviews: 10,
    },
    {
        name: 'Nike Slim Pants',
        slug: 'nike-slim-shirt1',
        image: '../images/p4.jpg',
        category: 'Pants',
        brand: 'NIKE',
        price: 120,
        countInStock: 10,
        description: 'High Quality Material',
        rating: 4,
        numReviews: 10,
    },
]